public inherited sharing class HttpConstants {
    public static final String METHOD_GET = 'GET';
    public static final String METHOD_POST = 'POST';
    public static final String METHOD_PUT = 'PUT';
    public static final String METHOD_PATCH = 'PATCH';
    public static final String METHOD_DELETE = 'DELETE';

    public static final Integer CODE_SUCCESS = 200;
    public static final Integer CODE_CREATED = 201;
    public static final Integer CODE_BAD_REQUEST = 400;
    public static final Integer CODE_FORBIDDEN = 403;
    public static final Integer CODE_NOT_FOUND = 404;
    public static final Integer CODE_CONFLICT = 409;
    public static final Integer CODE_INTERNAL_SERVER_ERROR = 500;

    public static final STRING HEADER_CONTENT_TYPE = 'Content-Type';
    public static final STRING HEADER_CONTENT_TYPE_JSON = 'application/json';
}
